Repository DIBTP-E2E/KFE3-dibtp, pull requests merged in 2025-08, with the labels that each got.

#244 feat: 위치 설정 UX 개선 및 리팩토링 (#232)
  apps/web/components/layout/header-icon/RegionLabel.tsx
  apps/web/components/location/AddressSearchButton.tsx
  apps/web/components/location/CurrentLocationButton.tsx
  apps/web/components/location/LocationDisplay.tsx
  apps/web/components/location/LocationHeader.tsx
  apps/web/components/location/LocationMap.tsx
  apps/web/components/location/LocationMapContainer.tsx
  apps/web/components/location/LocationSelector.tsx
  apps/web/components/location/index.ts
  apps/web/components/product-form/LocationInfoField.tsx
  apps/web/constants/cities.ts
  apps/web/constants/index.ts
  apps/web/hooks/location/index.ts
  apps/web/hooks/location/useDaumPostcode.ts
  apps/web/hooks/location/useGeolocation.ts
  apps/web/hooks/location/useKakaoGeocoder.ts
  apps/web/hooks/location/useKakaoMap.ts
  apps/web/hooks/location/useMapMarker.ts
  apps/web/hooks/my-info/useMyInfo.ts
  apps/web/hooks/users/useUserInfo.ts
  apps/web/middleware.ts
  apps/web/services/my-info/server/getMyInfo.ts
  apps/web/services/products/server/fetchProducts.ts
  apps/web/services/products/server/getMyProducts.ts
  apps/web/types/location/domain.ts
  apps/web/types/location/index.ts
  apps/web/types/location/postcode.ts
  apps/web/types/my-info/api.ts
  apps/web/types/product/api.ts
  apps/web/utils/common/external-script-loader.ts
  apps/web/utils/common/index.ts
  apps/web/utils/location/address-utils.ts
  apps/web/utils/products/product-mappers.ts
  packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
Labels: refactor, feat, fix

#246 [feat] 토스트 메시지 컴포넌트 생성 및 에러 핸들링 개선 (#226)
  apps/web/app/(pages)/mypage/profile/page.tsx
  apps/web/app/layout.tsx
  apps/web/components/mypage/LogoutButton.tsx
  apps/web/components/product-detail/BidButton.tsx
  apps/web/components/product-detail/ChatButton.tsx
  apps/web/components/product-detail/LikeButton.tsx
  apps/web/hooks/products/useProductForm.ts
  packages/tailwind-config/design-tokens/color-tokens/primitive-colors.css
  packages/tailwind-config/design-tokens/color-tokens/semantic-colors.css
  packages/tailwind-config/design-tokens/color-tokens/utility-colors.css
  packages/ui/package.json
  packages/ui/src/design-system/base-components/Button/Button.stories.tsx
  packages/ui/src/design-system/base-components/Button/Button.tsx
  packages/ui/src/design-system/base-components/IconButton/IconButton.stories.tsx
  packages/ui/src/design-system/base-components/IconButton/IconButton.tsx
  packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
  packages/ui/src/design-system/base-components/Toast/Toast.stories.tsx
  packages/ui/src/design-system/base-components/Toast/Toast.tsx
  packages/ui/src/design-system/base-components/Toast/index.ts
  packages/ui/src/design-system/base-components/Toast/utils/toast.tsx
  packages/ui/src/design-system/base-components/index.ts
  packages/ui/src/design-system/design-token-stories/colors/generated-tokens.ts
  packages/ui/src/utils/index.ts
  pnpm-lock.yaml
Labels: design, feat

#254 [pref] auth 확인이 필요한 네트워크 요청에서만 미들웨어가 동작하도록 성능 개선 (#250)
  apps/web/middleware.ts
Labels: perf

#258 [refactor] 리액트 아이콘 번들 최소화 #257
  apps/web/components/search/RecentKeywords.tsx
  packages/ui/src/design-system/base-components/FormMessage/FormMessage.tsx
  packages/ui/src/design-system/base-components/IconButton/IconButton.stories.tsx
  packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
  packages/ui/src/design-system/base-components/Input/components/PasswordToggle.tsx
Labels: refactor

#260 refactor : ProductCard에 detail_address prop 추가 및 관련 컴포넌트 수정 #252
  apps/web/components/bid-history/BidHistoryCard.tsx
  apps/web/components/products/ProductCard.tsx
  apps/web/components/products/ProductList.tsx
  apps/web/components/sales/SalesProductCard.tsx
  apps/web/components/sales/SalesProductList.tsx
  apps/web/types/bid/domain.ts
  apps/web/utils/bids/mapBidHistoryResponse.ts
  pnpm-lock.yaml
Labels: fix

#263 [feat] cookie를 사용하여 중복되는 인증 과정 제거 및 성능 개선 (#249)
  apps/web/app/(pages)/chat/[chatRoomId]/page.tsx
  apps/web/app/(pages)/mypage/(mypage)/page.tsx
  apps/web/app/(pages)/products/[productId]/(detail)/page.tsx
  apps/web/app/(pages)/products/[productId]/edit/page.tsx
  apps/web/app/api/bids/my/route.ts
  apps/web/app/api/bids/route.ts
  apps/web/app/api/favorites/route.ts
  apps/web/app/api/images/route.ts
  apps/web/app/api/my-info/route.ts
  apps/web/app/api/products/[productId]/route.ts
  apps/web/app/api/products/route.ts
  apps/web/app/api/products/status/route.ts
  apps/web/components/products/ProductList.tsx
  apps/web/constants/cookies.ts
  apps/web/constants/index.ts
  apps/web/lib/supabase/server/middleware.ts
  apps/web/server-actions/location/saveLocationAction.ts
  apps/web/services/my-info/client/fetchMyInfo.ts
  apps/web/services/my-info/server/getMyInfo.ts
  apps/web/services/products/server/getMyProducts.ts
  apps/web/services/products/server/getProducts.ts
  apps/web/services/products/server/index.ts
  apps/web/utils/auth/server/auth-utils.ts
  apps/web/utils/auth/server/index.ts
  apps/web/utils/auth/server/my-info-utils.ts
Labels: refactor, perf

#268 fix: 릴리즈 노트 자동화 시스템 개선 및 CHANGELOG.md 업데이트 기능 수정 #267
  .github/workflows/release.yml
  CHANGELOG.md
Labels: bug, fix

#271 fix: 릴리즈 노트 작성 자동화 오류 수정 (#267)
  .github/workflows/release.yml
  CHANGELOG.md
Labels: bug, fix

#270 fix: auth-utils 모듈 제거하여 barrel export 제거 (#269)
  apps/web/utils/auth/server/index.ts
Labels: HOTFIX, fix

#272 fix: 릴리즈 버전 중복 생성 문제 해결
  .github/workflows/release.yml
  CHANGELOG.md
  scripts/generate-release-notes.js
Labels: bug, fix

#274 [perf] prefetch 하는 layout 위치 수정하여 성능 개선 및 상품 상세 페이지 레이아웃 UI 개선 (#266)
  apps/web/app/(home)/layout.tsx
  apps/web/app/(home)/page.tsx
  apps/web/app/(pages)/(home)/page.tsx
  apps/web/app/(pages)/layout.tsx
  apps/web/app/(pages)/products/[productId]/(detail)/page.tsx
  apps/web/app/layout.tsx
  apps/web/components/layout/BottomNavigation.tsx
  apps/web/components/layout/header-icon/BackButton.tsx
  apps/web/components/layout/header-icon/CloseTextButton.tsx
  apps/web/components/layout/header/HeaderContainer.tsx
  apps/web/components/layout/header/SearchHeader/SearchHeader.tsx
  apps/web/components/product-detail/AuctionInfoLayout.tsx
  apps/web/components/product-detail/CurrentPrice.tsx
  apps/web/components/product-detail/LikeButton.tsx
  apps/web/components/product-detail/NextPrice.tsx
  apps/web/components/product-detail/ProductAddress.tsx
  apps/web/components/product-detail/ProductDescription.tsx
  apps/web/components/product-detail/ProductDetailHeader.tsx
  apps/web/components/product-detail/ProductFooter.tsx
  apps/web/components/product-detail/ProductImageCarousel.tsx
  apps/web/components/product-detail/ProductTitle.tsx
  apps/web/components/product-detail/UserInfoLayout.tsx
  apps/web/components/search/SearchDropDown.tsx
  packages/tailwind-config/design-tokens/index.css
Labels: design, refactor, perf

#279 refactor: 아직 구현되지 않은 기능의 UI 요소에 준비중 토스트 처리
  apps/web/app/(pages)/mypage/(mypage)/page.tsx
  apps/web/components/layout/header-icon/AlarmButton.tsx
  apps/web/components/mypage/MypageMenuItem.tsx
  apps/web/components/mypage/SettingsMenu.tsx
  apps/web/components/mypage/TradingMenu.tsx
Labels: design, refactor

#278 [fix] PWA Manager UI 가독성 개선 (#277)
  apps/web/components/shared/PWAManager.tsx
Labels: design, fix

#283 [hotfix] 로그인 후 인증 로직 누락되어 다시 middleware의 matcher 복구 (#282)
  apps/web/middleware.ts
Labels: HOTFIX, fix

#284 [refactor] 상품 상세 페이지 및 상품 리스트 리팩토링 #276
  apps/web/app/(pages)/products/[productId]/(detail)/page.tsx
  apps/web/components/product-detail/AuctionInfoLayout.tsx
  apps/web/components/product-detail/BidButton.tsx
  apps/web/components/product-detail/CurrentPrice.tsx
  apps/web/components/product-detail/LikeButton.tsx
  apps/web/components/product-detail/ProductDetailHeader.tsx
  apps/web/components/product-detail/ProductFooter.tsx
  apps/web/components/product-detail/StatusActionButton.tsx
  apps/web/components/product-detail/UserInfoLayout.tsx
  apps/web/components/products/ProductList.tsx
  apps/web/components/products/ProductThumb.tsx
  apps/web/components/shared/SkeletonBox.tsx
  apps/web/components/shared/index.ts
  apps/web/hooks/favorites/useFavoriteStatus.ts
  apps/web/hooks/my-info/useMyInfo.ts
  apps/web/hooks/products/useCurrentPrice.ts
  apps/web/hooks/users/useUserInfo.ts
  apps/web/services/favorites/client/fetchFavoriteStatus.ts
  apps/web/services/favorites/client/index.ts
  apps/web/services/my-info/server/getMyInfo.ts
  apps/web/services/products/server/getMyProducts.ts
  apps/web/services/products/server/getProducts.ts
  apps/web/types/my-info/api.ts
  apps/web/types/product/api.ts
  apps/web/utils/products/product-mappers.ts
Labels: refactor

#286 fix: 안정성을 위해 서비스워커 주석 처리
  apps/web/public/sw.js
Labels: bug, fix
