Repository DIBTP-E2E/KFE3-dibtp, pull requests merged in 2025-07, with the labels that each got.

#52 [bug] Web app에서 UI 패키지의 컴포넌트를 import 할 때 스타일이 적용되지 않는 이슈 해결 #50
  apps/web/app/(pages)/layout.tsx
  apps/web/app/(pages)/products/page.tsx
  apps/web/styles/globals.css
  packages/ui/package.json
Labels: bug, chore

#55 [chore] ui 패키지 내 절대경로 설정 #54
  apps/web/app/(pages)/products/page.tsx
  packages/ui/package.json
  packages/ui/src/design-system/base-components/Avatar/Avatar.tsx
  packages/ui/src/design-system/base-components/Badge/Badge.tsx
  packages/ui/src/design-system/base-components/Icons/Icon.tsx
  packages/ui/src/design-system/base-components/Input/Input.tsx
  packages/ui/src/design-system/base-components/Input/PasswordInput.tsx
  packages/ui/src/design-system/base-components/Input/components/PasswordToggle.tsx
  packages/ui/src/design-system/base-components/Label/Label.tsx
  packages/ui/src/design-system/base-components/index.ts
  packages/ui/src/design-system/design-token-stories/colors/PrimitiveColors.stories.tsx
  packages/ui/src/design-system/design-token-stories/colors/SemanticColors.stories.tsx
  packages/ui/src/design-system/design-token-stories/colors/UtilityColors.stories.tsx
  packages/ui/src/storybook-components/Section.tsx
  packages/ui/src/storybook-components/StoryPage.tsx
  packages/ui/src/utils/storybook/color-token-utils.ts
  packages/ui/tsconfig.json
Labels: chore

#68 [feat] 버튼 컴포넌트 생성
  packages/ui/src/design-system/base-components/Button/Button.stories.tsx
  packages/ui/src/design-system/base-components/Button/Button.tsx
  packages/ui/src/design-system/base-components/Button/index.ts
  packages/ui/src/design-system/base-components/index.ts
Labels: feat

#71 [feat] UI 패키지에 Thumbnail 컴포넌트 생성 #70
  packages/ui/src/design-system/base-components/Thumbnail/Thumbnail.stories.tsx
  packages/ui/src/design-system/base-components/Thumbnail/Thumbnail.tsx
  packages/ui/src/design-system/base-components/Thumbnail/index.ts
  packages/ui/src/design-system/base-components/index.ts
Labels: feat

#75 [feat] 이미지 업로드 및 스토리지 관리 기능 구현
  apps/web/app/api/images/route.ts
  apps/web/components/ui/ImageUpload.tsx
  apps/web/constants/index.ts
  apps/web/constants/product-images.ts
  apps/web/constants/storage-bucket.ts
  apps/web/lib/storage/index.ts
  apps/web/lib/storage/storage.ts
  apps/web/lib/validations/image.ts
  apps/web/lib/validations/index.ts
  apps/web/services/images/client/deleteImages.ts
  apps/web/services/images/client/index.ts
  apps/web/services/images/client/uploadImages.ts
  apps/web/services/images/index.ts
  apps/web/services/images/server/deleteFromStorage.ts
  apps/web/services/images/server/index.ts
  apps/web/services/images/server/uploadToStorage.ts
  apps/web/services/index.ts
  apps/web/types/image.ts
  apps/web/types/index.ts
  apps/web/utils/image/image-utils.ts
  apps/web/utils/image/index.ts
  apps/web/utils/index.ts
  packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
Labels: feat

#80 [feat] 상품 상세 조회 페이지 구현 #22
  apps/web/app/(pages)/products/[productId]/data.ts
  apps/web/app/(pages)/products/[productId]/page.tsx
  apps/web/components/product-detail/AuctionInfoLayout.tsx
  apps/web/components/product-detail/AuctionSummary.tsx
  apps/web/components/product-detail/BackButton.tsx
  apps/web/components/product-detail/BidButton.tsx
  apps/web/components/product-detail/ChatButton.tsx
  apps/web/components/product-detail/CurrentPrice.tsx
  apps/web/components/product-detail/ImageCounter.tsx
  apps/web/components/product-detail/LikeButton.tsx
  apps/web/components/product-detail/NextButton.tsx
  apps/web/components/product-detail/NextPrice.tsx
  apps/web/components/product-detail/PrevButton.tsx
  apps/web/components/product-detail/ProductDescription.tsx
  apps/web/components/product-detail/ProductDetailHeader.tsx
  apps/web/components/product-detail/ProductFooter.tsx
  apps/web/components/product-detail/ProductImageCarousel.tsx
  apps/web/components/product-detail/ProductTitle.tsx
  apps/web/components/product-detail/SellerAvatar.tsx
  apps/web/components/product-detail/SellerNickname.tsx
  apps/web/components/product-detail/UserInfoLayout.tsx
  apps/web/components/product-detail/index.ts
  apps/web/components/shared/Timer.tsx
  apps/web/components/shared/index.ts
Labels: feat

#82 fix: 이미지 bucket 변경으로 인해 수정 (#81)
  apps/web/constants/storage-bucket.ts
Labels: HOTFIX, fix

#90 [hotfix] 지원하지 않는 next font 최적화 옵션 제거 #89
  apps/web/components/product-detail/BackButton.tsx
  apps/web/hooks/products/useProductForm.ts
  apps/web/next.config.ts
Labels: bug, HOTFIX

#95 [feat] 상품 상세 페이지 서비스 함수 생성 및 데이터 fetch #91
  apps/web/app/(pages)/products/[productId]/page.tsx
  apps/web/components/products/ProductCard.tsx
  apps/web/components/products/ProductList.tsx
  apps/web/components/products/ProductThumb.tsx
  apps/web/components/shared/ProductBadge.tsx
  apps/web/services/products/fetchProductDetail.ts
  apps/web/services/products/fetchProducts.ts
  apps/web/types/product/api.ts
Labels: feat

#99 [feat] 상품 상세 페이지 라우팅 추가 #97
  apps/web/components/products/ProductCard.tsx
Labels: feat

#115 [fix] 홈페이지의 상품리스트 suspense 적용
  apps/web/app/(auth-pages)/location/page.tsx
  apps/web/app/(home)/page.tsx
  apps/web/components/products/ProductList.tsx
  apps/web/components/products/index.ts
Labels: fix

#102 [feat] 모바일 레이아웃 고정값에서 모바일 한정 반응형으로 수정 #88
  apps/web/app/(pages)/products/[productId]/page.tsx
  apps/web/app/layout.tsx
  apps/web/components/layout/BottomNavigation.tsx
  apps/web/components/layout/TopNavigation.tsx
  apps/web/components/product-detail/ProductDetailHeader.tsx
  apps/web/components/product-detail/ProductFooter.tsx
  packages/tailwind-config/design-tokens/index.css
Labels: design, feat

#117 [bug] 폰트 에러 다시 등장하여 next font 설정을 cdn에서 local 폰트로 수정 #98
  apps/web/app/layout.tsx
  apps/web/public/fonts/NotoSansKR-Light.woff2
  apps/web/public/fonts/NotoSansKR-Regular.woff2
  apps/web/public/fonts/NotoSansKR-SemiBold.woff2
  packages/tailwind-config/design-tokens/typography-tokens.css
  packages/tailwind-config/semantic-styles/typography-styles.css
Labels: bug

#121 refactor: 상품 타입 구조 개선
  apps/web/components/layout/BottomNavigation.tsx
  apps/web/components/product-register/AuctionEndTimeField.tsx
  apps/web/components/products/ProductCard.tsx
  apps/web/components/products/ProductThumb.tsx
  apps/web/components/shared/ProductBadge.tsx
  apps/web/constants/index.ts
  apps/web/constants/navigation.ts
  apps/web/constants/product-status.ts
  apps/web/services/products/fetchProductDetail.ts
  apps/web/services/products/fetchProducts.ts
  apps/web/services/products/mappers.ts
  apps/web/types/product/api.ts
  apps/web/types/product/domain.ts
  apps/web/types/product/form.ts
  apps/web/types/product/index.ts
Labels: refactor

#122 feat: 상품 목록 스켈레톤 UI 개선 및 지역별 필터링 기능 구현
  apps/web/components/products/ProductListSkeleton.tsx
  apps/web/services/products/fetchProducts.ts
Labels: design, feat

#131 fix: github actions에서 pnpm 설정 오류 수정 (#130)
  .github/workflows/release.yml
Labels: bug

#136 [chore] chromatic.yml 파일에서 누락된 build 단계 추가
  .github/workflows/chromatic.yml
Labels: bug, chore

#138 fix: release 액션에서 기존 태그 중복 오류 수정
  .github/workflows/release.yml
Labels: bug, fix

#142 fix: chromatic.yml 파일에서 turbo 명령어의 ui 호출 오탈자 수정 #141
  .github/workflows/chromatic.yml
Labels: bug, chore, fix

#147 fix: release 스크립트 squash merge 환경 대응 개선 (#146)
  .gitignore
  release_notes.md
  scripts/generate-release-notes.js
Labels: bug, fix

#149 docs: 릴리즈 노트 자동화를 CHANGELOG.md 형식으로 개선 (#148)
  CHANGELOG.md
  scripts/generate-release-notes.js
Labels: docs

#154 refactor: 인증 유틸리티 모듈 개선 및 미들웨어 정리 (#153)
  apps/web/app/api/images/route.ts
  apps/web/middleware.ts
  apps/web/utils/auth/auth-utils.ts
Labels: refactor, fix

#152 feat: 마이페이지 UI 및 로그아웃 기능 구현 (#151)
  apps/web/app/(pages)/mypage/layout.tsx
  apps/web/app/(pages)/mypage/page.tsx
  apps/web/components/mypage/ActivityCard.tsx
  apps/web/components/mypage/ActivityStats.tsx
  apps/web/components/mypage/LogoutButton.tsx
  apps/web/components/mypage/MypageHeader.tsx
  apps/web/components/mypage/MypageMenuItem.tsx
  apps/web/components/mypage/MypageSectionCard.tsx
  apps/web/components/mypage/SettingsMenu.tsx
  apps/web/components/mypage/TradingMenu.tsx
  apps/web/components/mypage/index.ts
  apps/web/constants/navigation.ts
  apps/web/lib/supabase/middleware.ts
  packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
  packages/ui/src/design-system/base-components/Icons/index.ts
Labels: design, feat

#162 [fix] IconButton import 문 경로 수정 이슈 해결 및 UI 패키지 내 절대경로 별칭을 @ 에서 @ui로 수정 #161
  apps/docs/.storybook/main.ts
  apps/web/components/layout/header-icon/CloseTextButton.tsx
  apps/web/components/layout/header-icon/HeaderIconButton.tsx
  packages/ui/src/design-system/base-components/Avatar/Avatar.tsx
  packages/ui/src/design-system/base-components/Badge/Badge.tsx
  packages/ui/src/design-system/base-components/Button/Button.stories.tsx
  packages/ui/src/design-system/base-components/Button/Button.tsx
  packages/ui/src/design-system/base-components/Button/index.ts
  packages/ui/src/design-system/base-components/IconButton/IconButton.stories.tsx
  packages/ui/src/design-system/base-components/IconButton/IconButton.tsx
  packages/ui/src/design-system/base-components/IconButton/index.ts
  packages/ui/src/design-system/base-components/Icons/Icon.tsx
  packages/ui/src/design-system/base-components/Icons/index.ts
  packages/ui/src/design-system/base-components/Input/Input.tsx
  packages/ui/src/design-system/base-components/Input/PasswordInput.tsx
  packages/ui/src/design-system/base-components/Input/components/PasswordToggle.tsx
  packages/ui/src/design-system/base-components/Label/Label.stories.tsx
  packages/ui/src/design-system/base-components/Label/Label.tsx
  packages/ui/src/design-system/base-components/Label/index.ts
  packages/ui/src/design-system/base-components/Thumbnail/Thumbnail.tsx
  packages/ui/src/design-system/base-components/Thumbnail/index.ts
  packages/ui/tsconfig.json
Labels: bug, HOTFIX, refactor, fix

#169 fix: ui 패키지 import 경로 오류 수정 (#167)
  packages/ui/src/design-system/base-components/Textarea/LabeledTextarea.tsx
  packages/ui/src/design-system/design-token-stories/colors/PrimitiveColors.stories.tsx
  packages/ui/src/design-system/design-token-stories/colors/SemanticColors.stories.tsx
  packages/ui/src/design-system/design-token-stories/colors/UtilityColors.stories.tsx
  packages/ui/src/storybook-components/Section.tsx
  packages/ui/src/storybook-components/StoryPage.tsx
  packages/ui/src/utils/storybook/color-token-utils.ts
Labels: bug

#183 fix: 누락된 import 수정사항 반영 (#182)
  apps/web/components/screen/SearchScreen/SearchScreen.tsx
  apps/web/components/search/index.ts
Labels: bug, HOTFIX

#186 [fix] 채팅 페이지 레이아웃 컴파일 에러 해결 #185
  apps/web/app/(pages)/chat/layout.tsx
Labels: bug, HOTFIX

#177 [feat] 현재 가격 UI 자동 업데이트 되도록 수정 #176
  apps/web/components/product-detail/AuctionInfoLayout.tsx
  apps/web/components/product-detail/CurrentPrice.tsx
  apps/web/components/product-detail/NextPrice.tsx
  apps/web/components/product-detail/ProductFooter.tsx
  apps/web/components/products/ProductCard.tsx
  apps/web/components/products/ProductList.tsx
  apps/web/constants/products/product-status.ts
  apps/web/hooks/products/index.ts
  apps/web/hooks/products/useCurrentPrice.ts
  apps/web/utils/products/calculateCurrentPrice.ts
Labels: feat

#190 [refactor] web app 내 @web 별칭을 점진적으로 사용 가능하도록 절대경로 별칭 추가 설정 #164
  apps/docs/.storybook/main.ts
  apps/web/components/product-register/ImageUpload.tsx
  apps/web/components/product-register/ProductRegisterForm.tsx
  apps/web/components/product-register/index.ts
  apps/web/tsconfig.json
Labels: refactor

#187 feat: bottomsheet 및 actionsheet 컴포넌트 추가 (#180)
  apps/web/app/layout.tsx
  packages/ui/src/design-system/base-components/ActionSheet/ActionSheet.stories.tsx
  packages/ui/src/design-system/base-components/ActionSheet/ActionSheet.tsx
  packages/ui/src/design-system/base-components/ActionSheet/index.ts
  packages/ui/src/design-system/base-components/BottomSheet/BottomSheet.stories.tsx
  packages/ui/src/design-system/base-components/BottomSheet/BottomSheet.tsx
  packages/ui/src/design-system/base-components/BottomSheet/hooks/index.ts
  packages/ui/src/design-system/base-components/BottomSheet/hooks/useBottomSheetGestures.ts
  packages/ui/src/design-system/base-components/BottomSheet/hooks/useBottomSheetState.ts
  packages/ui/src/design-system/base-components/BottomSheet/index.ts
  packages/ui/src/design-system/base-components/index.ts
Labels: design, feat

#199 fix: chromatic.yml 파일에서 chromatic-storybook 단계가 skip 되는 이슈 해결 (#198)
  .github/workflows/chromatic.yml
Labels: bug, chore

#200 [feat] 채팅 기능 domain과 api 인터페이스 정의와 채팅 생성 기능 구현 #191
  apps/web/app/(pages)/chat/[chatId]/layout.tsx
  apps/web/app/(pages)/chat/[chatId]/page.tsx
  apps/web/app/(pages)/chat/layout.tsx
  apps/web/app/(pages)/chat/page.tsx
  apps/web/app/(pages)/products/[productId]/page.tsx
  apps/web/app/api/chat/rooms/route.ts
  apps/web/app/api/user/region/route.ts
  apps/web/app/robots.txt
  apps/web/components/layout/header-icon/RegionLabel.tsx
  apps/web/components/layout/header/SearchHeader/SearchInput.tsx
  apps/web/components/product-detail/ChatButton.tsx
  apps/web/components/product-detail/UserInfoLayout.tsx
  apps/web/constants/routes/api.ts
  apps/web/hooks/chat/useCreateChatRoom.ts
  apps/web/services/chat/client/createChatRoom.ts
  apps/web/services/chat/server/createChatRoom.ts
  apps/web/services/user/client/fetchUserRegion.ts
  apps/web/services/user/server/getUserRegion.ts
  apps/web/types/chat/api.ts
  apps/web/types/chat/domain.ts
  apps/web/types/chat/index.ts
  apps/web/types/index.ts
  apps/web/types/lib/supabase-type.ts
  apps/web/types/user/api.ts
  apps/web/types/user/index.ts
  packages/ui/src/design-system/base-components/Button/Button.tsx
Labels: feat

#210 [feat] layout에 prefetch 하는 my info 데이터 추가 및 useMyInfo hook 생성 #206
  apps/web/app/api/my-info/route.ts
  apps/web/app/layout.tsx
  apps/web/components/layout/header-icon/RegionLabel.tsx
  apps/web/components/layout/header/SearchHeader/SearchInput.tsx
  apps/web/components/product-detail/ChatButton.tsx
  apps/web/constants/query-key.ts
  apps/web/constants/routes/api.ts
  apps/web/hooks/index.ts
  apps/web/hooks/my-info/index.ts
  apps/web/hooks/my-info/useMyInfo.ts
  apps/web/lib/query/server/index.ts
  apps/web/lib/query/server/prefetchMyInfo.ts
  apps/web/lib/query/server/prefetchUserQuery.ts
  apps/web/services/my-info/client/fetchMyInfo.ts
  apps/web/services/my-info/client/index.ts
  apps/web/services/my-info/server/getMyInfo.ts
  apps/web/services/my-info/server/index.ts
  apps/web/services/user/client/index.ts
  apps/web/services/user/server/index.ts
  apps/web/types/index.ts
  apps/web/types/my-info/api.ts
  apps/web/types/my-info/index.ts
  apps/web/types/user/api.ts
Labels: refactor, feat

#211 feat: 판매 내역 페이지 상품 액션 기능 구현 (#188)
  apps/web/app/(pages)/mypage/sales/layout.tsx
  apps/web/app/api/products/[productId]/route.ts
  apps/web/app/api/products/my/route.ts
  apps/web/app/api/products/status/route.ts
  apps/web/app/layout.tsx
  apps/web/components/products/ProductCard.tsx
  apps/web/components/products/ProductThumb.tsx
  apps/web/components/sales/SalesEmptyState.tsx
  apps/web/components/sales/SalesHistoryTabs.tsx
  apps/web/components/sales/SalesProductCard.tsx
  apps/web/components/sales/SalesProductList.tsx
  apps/web/components/sales/index.ts
  apps/web/components/sales/mockData.ts
  apps/web/components/search/RecentKeywords.tsx
  apps/web/components/shared/ProductBadge.tsx
  apps/web/constants/query-key.ts
  apps/web/constants/routes/api.ts
  apps/web/constants/routes/pages.ts
  apps/web/hooks/common/index.ts
  apps/web/hooks/common/useAppNavigation.ts
  apps/web/hooks/index.ts
  apps/web/hooks/products/index.ts
  apps/web/hooks/products/useCurrentPrice.ts
  apps/web/hooks/products/useMyProducts.ts
  apps/web/hooks/products/useProductActionMenu.ts
  apps/web/hooks/products/useProductActions.ts
  apps/web/hooks/search/useSearchAction.ts
  apps/web/hooks/search/useSearchDropdown.ts
  apps/web/services/products/client/fetchMyProducts.ts
  apps/web/services/products/client/index.ts
  apps/web/services/products/client/removeProduct.ts
  apps/web/services/products/client/shareProduct.ts
  apps/web/services/products/client/startAuction.ts
  apps/web/services/products/client/stopAuction.ts
  apps/web/services/products/client/updateProductStatus.ts
  apps/web/services/products/server/getMyProducts.ts
  apps/web/services/products/server/index.ts
  apps/web/services/products/server/updateProductState.ts
  apps/web/utils/products/filterProductsByStatus.ts
  packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
Labels: design, feat

#214 feat: 구매내역(입찰내역) 조회 기능 구현 (#212)
  apps/web/app/(pages)/mypage/bids/layout.tsx
  apps/web/app/(pages)/mypage/bids/page.tsx
  apps/web/app/api/bids/my/route.ts
  apps/web/components/bid-history/BidHistoryCard.tsx
  apps/web/components/bid-history/BidHistoryContainer.tsx
  apps/web/components/bid-history/BidHistoryDateFilter.tsx
  apps/web/components/bid-history/BidHistoryEmptyState.tsx
  apps/web/components/bid-history/BidHistoryFilter.tsx
  apps/web/components/bid-history/BidHistorySearchEmpty.tsx
  apps/web/components/bid-history/BidHistorySearchFilter.tsx
  apps/web/components/bid-history/index.ts
  apps/web/components/mypage/TradingMenu.tsx
  apps/web/constants/query-key.ts
  apps/web/constants/routes/pages.ts
  apps/web/hooks/bids/index.ts
  apps/web/hooks/bids/useBidDateFilter.ts
  apps/web/hooks/bids/useBidFilter.ts
  apps/web/hooks/bids/useBidHistory.ts
  apps/web/hooks/bids/useBidSearchFilter.ts
  apps/web/hooks/index.ts
  apps/web/hooks/products/useMyProducts.ts
  apps/web/hooks/products/useProductActions.ts
  apps/web/services/bids/client/fetchBidHistory.ts
  apps/web/services/bids/client/index.ts
  apps/web/services/bids/server/getBidHistory.ts
  apps/web/services/bids/server/index.ts
  apps/web/types/bid/api.ts
  apps/web/types/bid/domain.ts
  apps/web/types/bid/index.ts
  apps/web/types/index.ts
  apps/web/utils/bids/index.ts
  apps/web/utils/bids/mapBidHistoryResponse.ts
  apps/web/utils/date/formatDate.ts
  apps/web/utils/date/index.ts
Labels: design, feat

#225 [feat] 채팅 메시지 전송 및 수신 기능 및 채팅방 페이지 UI 구현 (#202)
  apps/web/app/(pages)/chat/[chatId]/page.tsx
  apps/web/app/(pages)/chat/[chatRoomId]/page.tsx
  apps/web/app/(pages)/chat/rooms/page.tsx
  apps/web/app/api/chat/messages/read/route.ts
  apps/web/app/api/chat/messages/route.ts
  apps/web/app/api/chat/messages/send/route.ts
  apps/web/app/api/chat/rooms/detail/route.ts
  apps/web/components/chat/ChatRoom/ChatRoom.tsx
  apps/web/components/chat/ChatRoom/ChatRoomNodata.tsx
  apps/web/components/chat/ChatRoom/MessageBubble.tsx
  apps/web/components/chat/ChatRoom/MessageInput.tsx
  apps/web/components/chat/ChatRoom/index.ts
  apps/web/components/chat/index.ts
  apps/web/constants/query-key.ts
  apps/web/hooks/chat/index.ts
  apps/web/hooks/chat/useChatMessages.ts
  apps/web/hooks/chat/useMarkMessagesAsRead.ts
  apps/web/hooks/chat/useRealtimeMessages.ts
  apps/web/hooks/chat/useSendMessage.ts
  apps/web/services/chat/client/fetchChatRoomDetail.ts
  apps/web/services/chat/client/fetchMessages.ts
  apps/web/services/chat/client/index.ts
  apps/web/services/chat/client/markMessagesAsRead.ts
  apps/web/services/chat/client/sendMessage.ts
  apps/web/services/chat/server/getChatRoomDetail.ts
  apps/web/services/chat/server/getMessages.ts
  apps/web/services/chat/server/index.ts
  apps/web/services/chat/server/markMessagesAsRead.ts
  apps/web/services/chat/server/sendMessage.ts
  apps/web/types/chat/api.ts
  apps/web/types/chat/domain.ts
  packages/ui/src/design-system/base-components/Icons/assets/Icons.ts
Labels: feat

#230 fix: 여러 메시지 읽을 때만 생기는 무한 루프 현상 제거 (#229)
  apps/web/app/api/chat/messages/read/route.ts
  apps/web/components/chat/ChatRoom/ChatRoom.tsx
Labels: bug, HOTFIX, fix

#235 fix: 빌드 에러 수정, params 타입 수정 (#234)
  apps/web/app/api/users/[userId]/route.ts
Labels: bug, fix

#233 feat: PWA 설정 구현 (#221)
  apps/web/app/layout.tsx
  apps/web/app/manifest.json
  apps/web/app/manifest.ts
  apps/web/components/login/LoginButton.stories.tsx
  apps/web/components/shared/PWAManager.tsx
  apps/web/components/shared/index.ts
  apps/web/hooks/common/useAppNavigation.ts
  apps/web/next.config.ts
  apps/web/package.json
  apps/web/public/sw.js
  pnpm-lock.yaml
Labels: chore, feat
