Repository DIBTP-E2E/KFE3-dibtp, pull requests merged in 2025-06, with the labels that each got.

#7 [fix] Noto Sans KR 폰트가 웹에서 반영되지 않는 이슈 수정 #5
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  apps/web/next.config.ts
  apps/web/providers/QueryProvider.tsx
  apps/web/styles/globals.css
  packages/tailwind-config/shared-styles.css
  packages/ui/src/global.css
Labels: bug

#8 [fix] eslint 가 수정된 파일 위치를 찾지 못하는 이슈를 해결하기 위한 lefthook.yml 파일 수정 #6
  lefthook.yml
Labels: bug

#37 [fix] 기존 ui 패키지 내에 정의된 color 디자인 토큰 스토리 문서 수정 #33
  packages/tailwind-config/design-tokens/color-tokens/primitive-colors.css
  packages/tailwind-config/design-tokens/color-tokens/scale-colors.css
  packages/tailwind-config/design-tokens/color-tokens/semantic-colors.css
  packages/tailwind-config/semantic-styles/colors-styles.css
  packages/ui/package.json
  packages/ui/scripts/generate-tokens.ts
  packages/ui/scripts/tsconfig.json
  packages/ui/src/design-system/base-components/Input/disable.txt
  packages/ui/src/design-system/design-tokens/Colors.stories.tsx
  packages/ui/src/design-system/design-tokens/PrimitiveColors.stories.tsx
  packages/ui/src/design-system/design-tokens/ScaleColors.stories.tsx
  packages/ui/src/design-system/design-tokens/SemanticColors.stories.tsx
  packages/ui/src/design-system/design-tokens/Typography.stories.tsx
  packages/ui/src/design-system/design-tokens/colors.ts
  packages/ui/src/design-system/design-tokens/generated-tokens.ts
  packages/ui/src/design-system/design-tokens/index.ts
  packages/ui/src/design-system/design-tokens/typography.ts
  packages/ui/src/global.css
  packages/ui/src/globals.css
  packages/ui/src/storybook-components/ColorList.tsx
  packages/ui/src/storybook-components/ColorPalette.tsx
  packages/ui/src/storybook-components/HowToUse.tsx
  packages/ui/src/storybook-components/HowToUseClass.tsx
  packages/ui/src/storybook-components/PageTitle.tsx
  packages/ui/src/storybook-components/Section.tsx
  packages/ui/src/storybook-components/SectionTitle.tsx
  packages/ui/src/storybook-components/StoryPage.tsx
  packages/ui/src/storybook-components/index.ts
  packages/ui/src/utils/storybook/color-token-utils.ts
  packages/ui/src/utils/storybook/index.ts
  packages/ui/tsconfig.json
  pnpm-lock.yaml
Labels: fix

#40 [refactor] 색상 디자인 토큰 계층 구조의 이름을 Semantic, Scale, Primitive 에서 Utility, Semantic, Primitive 로 수정 #38
  packages/tailwind-config/design-tokens/color-tokens/scale-colors.css
  packages/tailwind-config/design-tokens/color-tokens/semantic-colors.css
  packages/tailwind-config/design-tokens/color-tokens/utility-colors.css
  packages/tailwind-config/design-tokens/index.css
  packages/tailwind-config/semantic-styles/colors-styles.css
  packages/ui/scripts/generate-tokens.ts
  packages/ui/src/design-system/design-token-stories/Typography.stories.tsx
  packages/ui/src/design-system/design-token-stories/colors/PrimitiveColors.stories.tsx
  packages/ui/src/design-system/design-token-stories/colors/SemanticColors.stories.tsx
  packages/ui/src/design-system/design-token-stories/colors/UtilityColors.stories.tsx
  packages/ui/src/design-system/design-token-stories/colors/generated-tokens.ts
  packages/ui/src/design-system/design-token-stories/typography.ts
  packages/ui/src/design-system/design-tokens/ScaleColors.stories.tsx
  packages/ui/src/design-system/design-tokens/SemanticColors.stories.tsx
  packages/ui/src/storybook-components/ColorList.tsx
  packages/ui/src/storybook-components/ColorPalette.tsx
  packages/ui/src/utils/storybook/color-token-utils.ts
Labels: docs, chore

#46 [feat] 디자인 시스템 Textarea 컴포넌트 추가
  packages/ui/src/design-system/base-components/Input/index.ts
  packages/ui/src/design-system/base-components/Textarea/LabeledTextarea.tsx
  packages/ui/src/design-system/base-components/Textarea/Textarea.tsx
  packages/ui/src/design-system/base-components/Textarea/index.ts
  packages/ui/src/design-system/base-components/Textarea/stories/LabeledTextarea.stories.tsx
  packages/ui/src/design-system/base-components/Textarea/stories/Textarea.stories.tsx
Labels: design, feat
